apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginxdaemonset  
spec:
  selector:
    matchLabels:
      app: nginxdaemonset
  template:
    metadata:
      labels:
        app: nginxdaemonset
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
        
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
